### ISSUE TITLE
Collaborators Commit

### ISSUE THREAD

**Issue by ernest-phillips** [ernest-phillips/ernest-phillips.github.io#4]
Could you please create a PR for a commit to the `collaborators.md` file?
I am trying to initiate the discussions board for this repo.

Just adding your name is fine. 

CC: @francisfuzz @yamiacat

**Comment by francisfuzz** [comment]
Thanks for the ping! 

🔪  Cut https://github.com/ernest-phillips/ernest-phillips.github.io/pull/6 to support this :v:

**Comment by yamiacat** [comment]
Opened https://github.com/ernest-phillips/ernest-phillips.github.io/pull/8

You've already got 3 contributors on the front page so I'll request Discussions for this repo!
